author: Yevhenii Bykov
show_downloads: true
title: Find text on images
description: A small python script to find text on images. Uses EasyOCR and thefuzz
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
